
coin_list = {"btc": "bitcoin", 
             "eth": "ethereum",
             "usdt": "tether",
             "usdc": "usd-coin",
             "bnb": "binancecoin",
             "xrp": "binance-peg-xrp",
             "sol": "solana",
             "doge": "dogecoin",
             "dot": "binance-peg-polkadot",
             "shib": "shiba-inu",
             "dai": "dai",
             "matic": "matic-network",
             "poligon": "matic-network",
             "trx": "tron",
             "steth": "staked-ether",
             "avax": "binance-peg-avalanche",
             "uni": "uniswap",
             "wbtc": "wrapped-bitcoin",
             "okb": "okb",
             "leo": "leo-token",
             "ltc": "litecoin",
             "atom": "cosmos",
             "cosmos": "cosmos",
             "link": "chainlink",
             "etc": "ethereum-classic",
             "xlm": "stellar",
             "ftt": "ftx-token",
             "near": "near",
             "cro":"crypto-com-chain",
             "xmr":"monero",
             "algo":"algorand",
             "bch":"bitcoin-cash",
             "lunc":"terra-luna",
             "qnt":"quant-network",
             "flow":"flow",
             "vet":"vechain",
             "ape":"apecoin",
             "fil":"filecoin",
             "icp":"internet-computer",
             "xcn":"chain-2",
             "hbar":"hedera-hashgraph",
             "frax":"frax",    
             "egld":"elrond-erd-2",   
             "xtz":"tezos",
             "sand":"the-sandbox",
             "mana":"decentraland",
             "axs":"axie-infinity",
             "eos":"eos",
             "chz":"chiliz",
             "aave":"aave",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             }
             


# while True:
#     key = input('Coin: ')

#     if key in coin_list:
#         print(coin_list.get(key))
#     else:
#         print('False')