
coin_list = {"btc": "bitcoin", 
             "eth": "ethereum",
             "usdt": "tether",
             "usdc": "usd-coin",
             "bnb": "binancecoin",
             "xrp": "binance-peg-xrp",
             "sol": "solana",
             "doge": "dogecoin",
             "dot": "binance-peg-polkadot",
             "shib": "shiba-inu",
             "dai": "dai",
             "matic": "matic-network",
             "poligon": "matic-network",
             "trx": "tron",
             "steth": "staked-ether",
             "avax": "binance-peg-avalanche",
             "uni": "uniswap",
             "wbtc": "wrapped-bitcoin",
             "okb": "okb",
             "leo": "leo-token",
             "ltc": "litecoin",
             "atom": "cosmos",
             "cosmos": "cosmos",
             "link": "chainlink",
             "etc": "ethereum-classic",
             "xlm": "stellar",
             "ftt": "ftx-token",
             "near": "near",
             "cro":"crypto-com-chain",
             "xmr":"monero",
             "algo":"algorand",
             "bch":"bitcoin-cash",
             "lunc":"terra-luna",
             "qnt":"quant-network",
             "flow":"flow",
             "vet":"vechain",
             "ape":"apecoin",
             "fil":"filecoin",
             "icp":"internet-computer",
             "xcn":"chain-2",
             "hbar":"hedera-hashgraph",
             "frax":"frax",    
             "egld":"elrond-erd-2",   
             "xtz":"tezos",
             "sand":"the-sandbox",
             "mana":"decentraland",
             "axs":"axie-infinity",
             "eos":"eos",
             "chz":"chiliz",
             "aave":"aave",
             "ht":"huobi-token",
             "tkx":"tokenize-xchange",
             "ldo":"lido-dao",
             "chz":"chiliz",
             "kcs":"kucoin-shares",
             "mkr":"maker",
             "cusdc":"compound-usd-coin",
             "bsv":"bitcoin-cash-sv",
             "usdp":"paxos-standard",
             "tusd":"true-usd",
             "ethw":"ethereum-pow-iou",
             "btt":"bittorrent",
             "xec":"ecash",
             "miota":"iota",
             "grt":"the-graph",
             "cake":"pancakeswap-token",
             "gt":"gatechain-token",
             "osmo":"osmosis",
             "cdai":"cdai",
             "hnt":"helium",
             "snx":"havven",
             "neo":"neo",
             "ceth":"compound-ether",
             "xrd":"radix",
             "evmos":"evmos",
             "ftm":"fantom",
             "cspr":"casper-network",
             "ar":"arweave",
             "paxg":"pax-gold",
             "ens":"ethereum-name-service",
             "nexo":"nexo",
             "crv":"curve-dao-token",
             "bit":"bitdao",
             "zil":"zilliqa",
             "rune":"thorchain",
             "twt":"trust-wallet-token",
             "dash":"dash",
             "klay":"klay-token",
             "cel":"celsius-degree-token",
             "xdc":"xdce-crowd-sale",
             "enj":"enjincoin",
             "bat":"basic-attention-token",
             "rpl":"rocket-pool",
             "kava":"kava",
             "fxs":"frax-share",
             "xaut":"tether-gold",
             "stx":"blockstack",
             "mina":"mina-protocol",
             "qmall":"qmall",
             "ada":"cardano",
             "cardano":"cardano",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             "":"",
             }
             


# while True:
#     key = input('Coin: ')

#     if key in coin_list:
#         print(coin_list.get(key))
#     else:
#         print('False')